---
# tasks file for import_system_tables
  - name: Insert Command
    sap_function_call:
      ZSXPG_COMMAND_INSERT:
        NAME: 'ZTABEXP'
        OPSYSTEM: 'Linux'
        OPCOMMAND: 'R3trans'
        PARAMETERS: '-w /tmp/import_ecc.log /tmp/import.ctl'
    register: comm_insert

  - debug: var=comm_insert

  - name: Execute Command
    sap_function_call:
      SXPG_COMMAND_EXECUTE:
        NAME: "ZTABEXP"
    register: comm_execute

  - debug: var=comm_execute