---
# tasks file for copy_exp_ctl
  - name: copy exp.ctl file
    template:
      src: exp.ctl
      dest: /tmp/exp.ctl
      group: sapsys
      owner: "{{ lookup('ini','sid section=SAP file={{ filepath }}')|lower }}adm"
      force: yes
    become: yes
    vars:
      filepath: "{{ lookup('env','HOME') }}/.config/sap_config.ini"
